---
title: "An Illustrated Guide to Targeted Minimum Loss-based Estimation"
author: "Katherine Hoffman"
draft: true
date: 2020-10-10T21:13:14-05:00
categories: ["statistics","R"]
math: true
tags: ["statistics","causal inference","R","lmtp","TMLE","Targeted Maximum Likelihood Estimation","introduction to TMLE","targeted learning"]
output: 
  html_document:
    toc: true
    toc_float: true
    smart: false
---



<pre class="r"><code>library(kableExtra)</code></pre>
<p>Hello! I’m excited that you’re excited to learn about Targeted Maximum Likelihood Estimation (TMLE). I’ve tried to lay out TMLE in the simplest terms possible for an applied analyst who wants to understand the motivation and/or algorithm behind TMLE.</p>
<p>For better or for worse, I interpret statistical algorithms very visually, and the way I learned TMLE was by tracking every single step with a little colored data frame and pseudo-<code>R</code> code. I eventually formalized that thought process into a one page “cheat sheet” in case it can help anyone else:</p>
<p>It is available as an 8.5x11" pdf on my <a href="https://github.com/hoffmakl/CI-visual-guides/blob/master/visual-guides/TMLE.pdf">Github</a> in case you’d like to print it out for reference.</p>
<p>I’ll now discuss the motivation behind TMLE, the algorithm (step by step, with real <code>R</code> code), and a tiny bit on <em>why</em> it works and where you can learn more.</p>
<hr />
<div id="tmle-in-two-sentences" class="section level1">
<h1>TMLE in two sentences</h1>
<ul>
<li><p>The general form of Targeted Maximum Likelihood Estimation (TMLE) allows you to <strong>estimate a statistical estimand of interest using</strong>:</p>
<ol style="list-style-type: decimal">
<li><p>the expected outcome of an individual, given the treatment they received and their baseline confounders</p></li>
<li><p>the probability an individual received the treatment of interest, given their baseline confounders (propensity score)</p></li>
</ol></li>
<li><p>These estimates can come from flexible statistical models we commonly categorize as machine learning, but the <strong>overall estimate of the treatment effect will still have valid confidence intervals</strong>.</p></li>
</ul>
<hr />
<div id="wait-what-about-causal-inference" class="section level3">
<h3>Wait, what about causal inference??</h3>
<p>Now you might be thinking, “Wait a second! I only ever hear about TMLE in the context of causal inference.” It is true that TMLE is often talked about in the context of causal inference; however, by itself, TMLE is not causal inference. TMLE is a statistical estimation method which can be used for estimating parameters that do (or don’t!) have a causal interpretation.</p>
<p>TMLE was developed for causal inference because those who apply causal inference ideology to their work spend <em>so much time</em> trying to get the identification part (1) and (2) of causal inference correct, that they don’t want to “waste” that time by proceeding to use estimation algorithms which are known to place unreasonable assumptions on the distribution of the data.</p>
<p>This brings me to my last point of motivation.</p>
</div>
<div id="why-would-i-pick-tmle-over-other-statistical-estimation-algorithms" class="section level3">
<h3>Why would I pick TMLE over other statistical estimation algorithms?</h3>
<p>Because TMLE allows you to use machine learning algorithms on the backend of its estimation, that means you’re placing <em>minimal assumptions</em> on the underlying distribution of your data. However, TMLE still has a formula for obtaining valid confidence intervals. That’s so important!</p>
<p>Flexible machine learning models (EX: random forest, LASSO, neural nets) used on their own generally only allow us to predict, not to make statistical inference. They often have the wrong bias variance tradeoff for any particular exposure, or predictor, because their goal is to optimize prediction of an outcome.</p>
<p>TMLE uses some clever math, and something called an <strong>efficient influence function</strong> to solve this. More on that later; let’s talk about the algorithm.</p>
</div>
</div>
<div id="the-tmle-algorithm" class="section level1">
<h1>The TMLE Algorithm</h1>
<p>Initial set up: Load libraries, set seed, and simulate data</p>
<p><img src="/img/tmle/1_data_structure.png" style="width:80.0%" /></p>
<pre class="r"><code>library(tidyverse, quietly=T)</code></pre>
<pre><code>## ── Attaching packages ───────────────── tidyverse 1.3.0 ──</code></pre>
<pre><code>## ✓ ggplot2 3.3.2     ✓ purrr   0.3.4
## ✓ tibble  3.0.3     ✓ dplyr   1.0.2
## ✓ tidyr   1.1.2     ✓ stringr 1.4.0
## ✓ readr   1.3.1     ✓ forcats 0.5.0</code></pre>
<pre><code>## ── Conflicts ──────────────────── tidyverse_conflicts() ──
## x dplyr::filter()     masks stats::filter()
## x dplyr::group_rows() masks kableExtra::group_rows()
## x dplyr::lag()        masks stats::lag()</code></pre>
<pre class="r"><code>set.seed(7)

# Superlearner functions from Ivan
#source(&quot;sl.r&quot;)

# using data generating code from Miguel Angel Luque Fernandez&#39; tutorial
generate_data &lt;- function(n){
    w1 &lt;- rbinom(n, size=1, prob=0.5)
    w2 &lt;- rbinom(n, size=1, prob=0.65)
    w3 &lt;- round(runif(n, min=0, max=4), digits=3)
    w4 &lt;- round(runif(n, min=0, max=5), digits=3)
    A  &lt;- rbinom(n, size=1, prob= plogis(-0.4 + 0.2*w2 + 0.15*w3 + 0.2*w4 + 0.15*w2*w4))
    # counterfactual
    Y_1 &lt;- rbinom(n, size=1, prob= plogis(-1 + 1 -0.1*w1 + 0.3*w2 + 0.25*w3 + 0.2*w4 + 0.15*w2*w4))
    Y_0 &lt;- rbinom(n, size=1, prob= plogis(-1 + 0 -0.1*w1 + 0.3*w2 + 0.25*w3 + 0.2*w4 + 0.15*w2*w4))
    # Observed outcome
    Y &lt;- Y_1*A + Y_0*(1 - A)
    # return data.frame
    tibble(w1, w2, w3, w4, A, Y, Y_1, Y_0)
}

# observations N
n &lt;- 10000

# full data set, including Y0 and Y0
dat_full &lt;- generate_data(n)</code></pre>
<p>Our estimate of interest here is going to be the mean difference in outcomes if everyone had recevied the treatment compared to if everyone had not received the treatment. If we were to go through the whole causal inference identification process (AKA the very careful thinking half of causal inference), this might be identifiable as the Average Treatment Effect, or ATE.</p>
<p>Since we have simulated data, we can generate what the outcome would actually look like if everyone were to receive treatment and then if everyone were to not receive treatment, and we can take the mean difference.</p>
<pre class="r"><code># calculate the true psi if we saw both outcomes
true_psi &lt;- mean(dat_full$Y_1 - dat_full$Y_0)
round(true_psi,3)</code></pre>
<pre><code>## [1] 0.192</code></pre>
<p>Cool, so the true ATE for our is 0.192. Since our outcome is binary, that translates to a `19.2% difference in outcomes if everyone were to receive the treatment of interest. That means if A huge effect!</p>
<pre class="r"><code># make a data set with observed data only
dat_obs &lt;- dat_full %&gt;%
  select(-Y_1,-Y_0)</code></pre>
</div>
<div id="step-1" class="section level1">
<h1>Step 1:</h1>
<p>Estimate the expected value of the outcome using treatment and confounders as predictors.</p>
<p><span class="math display">\[Q(A,W) = \mathrm{E}[Y|A,W]\]</span></p>
<pre class="r"><code>Q &lt;- glm(Y ~ w1 + w2 + w3 + w4 + A, data = dat_obs, family=binomial)</code></pre>
<pre class="r"><code># Calculate SEs -----------------------------------------------------------

ic &lt;- (dat_obs$Y - Q_A_update) * H + Q_1_update + Q_0_update
tmle_se &lt;- sqrt(var(ic)/nrow(dat_obs))

ci_lo &lt;- tmle_psi - 1.96*tmle_se
ci_hi &lt;- tmle_psi + 1.96*tmle_se

pval &lt;- 2 * (1 - pnorm(abs(tmle_psi / tmle_se)))


# Compare with TMLE package -----------------------------------------------------------

tmle_fit &lt;- tmle::tmle(Y, A, X_A,
                       gbound = .000000001, # trying 
                       Q.SL.library = lib, g.SL.library = lib)
tmle_fit$epsilon # mine are different :(
tmle_fit$estimates$ATE</code></pre>
<p><img src="/img/tmle/2_outcome_fit.png" style="width:70.0%" /></p>
<p>Then predict the outcome for every observation under three scenarios:</p>
<p><strong>1. If every observation received the treatment they <em>actually</em> received.</strong></p>
<p><span class="math display">\[Q(A,W) = \mathrm{E}[Y|A,W]\]</span></p>
<p><img src="/img/tmle/3_QA.png" style="width:50.0%" /></p>
<pre class="r"><code>Q_A &lt;- predict(Q, type=&quot;response&quot;)
kable(head(Q_A))</code></pre>
<table>
<thead>
<tr>
<th style="text-align:right;">
x
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
0.7989757
</td>
</tr>
<tr>
<td style="text-align:right;">
0.7948479
</td>
</tr>
<tr>
<td style="text-align:right;">
0.8348842
</td>
</tr>
<tr>
<td style="text-align:right;">
0.7992942
</td>
</tr>
<tr>
<td style="text-align:right;">
0.7315107
</td>
</tr>
<tr>
<td style="text-align:right;">
0.5590003
</td>
</tr>
</tbody>
</table>
<p>Remember we’re talking about a binary treatment for this tutorial.</p>
<p><strong>2. If every observation received the treatment.</strong></p>
<p><span class="math display">\[Q(1,W) = \mathrm{E}[Y|1,W]\]</span></p>
<p><img src="/img/tmle/4_Q1.png" style="width:80.0%" /></p>
<pre class="r"><code>X_A1 &lt;- dat_obs %&gt;% mutate(A = 1)  # data set where everyone received treatment
Q_1 &lt;- predict(Q, newdata = X_A1, type=&quot;response&quot;)
kable(head(Q_1))</code></pre>
<table>
<thead>
<tr>
<th style="text-align:right;">
x
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
0.7989757
</td>
</tr>
<tr>
<td style="text-align:right;">
0.7948479
</td>
</tr>
<tr>
<td style="text-align:right;">
0.8348842
</td>
</tr>
<tr>
<td style="text-align:right;">
0.7992942
</td>
</tr>
<tr>
<td style="text-align:right;">
0.8766217
</td>
</tr>
<tr>
<td style="text-align:right;">
0.5590003
</td>
</tr>
</tbody>
</table>
<p><strong>3. If every observation received the control.</strong></p>
<p><span class="math display">\[Q(0,W) = \mathrm{E}[Y|0,W]\]</span></p>
<p><img src="/img/tmle/5_Q1.png" style="width:80.0%" /></p>
<pre class="r"><code>X_A0 &lt;- dat_obs %&gt;% mutate(A = 0) # data set where no one received treatment
Q_0 &lt;- predict(Q, newdata = X_A0, type=&quot;response&quot;)</code></pre>
<pre class="r"><code># estimate g --------------------------------------------------------------

g &lt;- glm(A ~ w1 + w2 + w3 + w4, data = dat_obs, family=binomial)

# predictions for Q -------------------------------------------------------

H_1 &lt;- 1/predict(g, type=&quot;response&quot;)
H_0 &lt;- -1/(1-predict(g, type=&quot;response&quot;))

# prep data to fit the clever covariate
dat_cc &lt;-
  dat_obs %&gt;%
  mutate(Q_A = Q_A,
         H = case_when(A == 1 ~ H_1,
                       A == 0 ~ H_0)) %&gt;%
  select(Y, A, Q_A, H)

# fit parametric working model - this will ALWAYS be the working model
glm_fit &lt;- glm(Y ~ -1 + offset(qlogis(Q_A)) + H, data=dat_cc, family=binomial)

# get epsilon
eps &lt;- coef(glm_fit)
# also get H as a vector (for Q_A_update)
H &lt;- dat_cc$H

# update expected outcome estimates (Q star) ------------------------------

# update
Q_1_update &lt;- plogis(qlogis(Q_1) + eps*H_1)
Q_0_update &lt;- plogis(qlogis(Q_0) + eps*H_0)
Q_A_update &lt;- plogis(qlogis(Q_A) + eps*H)

# Estimate ATE ------------------------------------------------------------

# get the ATE TMLE
tmle_psi &lt;- mean(Q_1_update - Q_0_update)

# compare to true parameter
tmle_psi</code></pre>
<pre><code>## [1] 0.1887145</code></pre>
<pre class="r"><code>true_psi </code></pre>
<pre><code>## [1] 0.1918</code></pre>
<p>#Step 2:</p>
<p>Estimate the probability of treatment, given confounders. Note that this quantity is often called a <strong>propensity score</strong>, as in it gives the <em>propensity</em> that an observation will receive a treatment of interest.</p>
<p><span class="math inline">\(g(W) = Pr(A=1|W)\)</span></p>
<p><img src="/img/tmle/6_treatment_fit.png" style="width:60.0%" />
<img src="/img/tmle/7_H1.png" style="width:60.0%" />
<img src="/img/tmle/8_H0.png" style="width:70.0%" />
<img src="/img/tmle/9_HA.png" style="width:50.0%" />
<img src="/img/tmle/10_logistic_regression.png" />
<img src="/img/tmle/11_epsilon.png" style="width:50.0%" />
<img src="/img/tmle/12_update_Q1.png" style="width:70.0%" />
<img src="/img/tmle/13_update_Q0.png" style="width:70.0%" />
<img src="/img/tmle/14_compute_ATE.png" style="width:60.0%" />
<img src="/img/tmle/15_ses.png" style="width:100.0%" /></p>
<pre class="r"><code># set SL libraries
lib &lt;- c(&#39;SL.speedglm&#39;, # faster glm
         &#39;SL.glmnet&#39;, # lasso
         &#39;SL.ranger&#39;, # random forest
         &#39;SL.earth&#39;)  #


# estimate Q --------------------------------------------------------------

Y &lt;- dat_obs$Y
X_Y &lt;- dat_obs %&gt;% select(-Y)

Q &lt;- SuperLearner(Y = Y, X = X_Y,
                    family=binomial(),
                    SL.library=lib,
                    # metalearner = NNloglik for binary outcomes, NNLS for continuous
                    method = method.NNloglik,
                    # 5-fold cross validation
                    cvControl = list(V = 5))

# estimate g --------------------------------------------------------------

A &lt;- dat_obs$A
X_A &lt;- dat_obs %&gt;% select(-Y, -A)

g &lt;- SuperLearner(Y = A, X = X_A,
                    family=binomial(),
                    SL.library=lib,
                    # metalearner = NNloglik for binary outcomes, NNLS for continuous
                    method = method.NNloglik,
                    # 5-fold cross validation
                    cvControl = list(V = 5))


# predictions for Q -------------------------------------------------------

Q_A &lt;- predict(Q)$pred

X_Y_A1 &lt;- X_Y %&gt;% mutate(A = 1) 
Q_1 &lt;- predict(Q, newdata = as.data.frame(X_Y_A1))$pred

X_Y_A0 &lt;- X_Y %&gt;% mutate(A = 0)
Q_0 &lt;- predict(Q, newdata = X_Y_A0)$pred


# create clever covariate -------------------------------------------------

H_1 &lt;- 1/predict(g)$pred
H_0 &lt;- -1/(1-predict(g)$pred)

# prep data to fit the clever covariate
dat_cc &lt;-
  dat_obs %&gt;%
  mutate(Q_A = as.vector(Q_A),
         H = case_when(A == 1 ~ H_1,
                       A == 0 ~ H_0)) %&gt;%
  select(Y, A, Q_A, H)

# fit parametric working model
glm_fit &lt;- glm(Y ~ -1 + offset(qlogis(Q_A)) + H, data=dat_cc, family=binomial)
# get epsilon
eps &lt;- coef(glm_fit)
# also get H as a vector (for Q_A_update)
H &lt;- dat_cc$H

# update expected outcome estimates (Q star) ------------------------------

# update
Q_1_update &lt;- plogis(qlogis(Q_1) + eps*H_1)
Q_0_update &lt;- plogis(qlogis(Q_0) + eps*H_0)
Q_A_update &lt;- plogis(qlogis(Q_A) + eps*H)

# Estimate ATE ------------------------------------------------------------

# get the ATE TMLE
tmle_psi &lt;- mean(Q_1_update - Q_0_update)

# compare to true parameter
tmle_psi
true_psi 


# Calculate SEs -----------------------------------------------------------

ic &lt;- (dat_obs$Y - Q_A_update) * H + Q_1_update + Q_0_update
tmle_se &lt;- sqrt(var(ic)/nrow(dat_obs))

ci_lo &lt;- tmle_psi - 1.96*tmle_se
ci_hi &lt;- tmle_psi + 1.96*tmle_se

pval &lt;- 2 * (1 - pnorm(abs(tmle_psi / tmle_se)))


# Compare with TMLE package -----------------------------------------------------------

tmle_fit &lt;- tmle::tmle(Y, A, X_A,
                       gbound = .000000001, # trying 
                       Q.SL.library = lib, g.SL.library = lib)
tmle_fit$epsilon # mine are different :(
tmle_fit$estimates$ATE</code></pre>
<p>Essentially, you start with the estimate of an individual’s outcome given their treatment and baseline covariates, and you update that estimate using the probability an individual received the treatment given their baseline covariates. Every time you update that estimate, you remove more of the bias that naturally exists in your observational data.</p>
</div>
<div id="why-should-i-bother-with-tmle" class="section level1">
<h1>Why should I bother with TMLE?</h1>
<p>Before I show an applied example of TMLE, I want to explain why I prefer TMLE to other propensity score estimation methods. In short, it is because because you don’t need to fit any certain type of regression to get your final estimates. You can use any estimator you want – a generalized linear model, splines, random forests, gradient boosting, neural nets, honestly anything – to get the initial probability estimates. You can actually use <em>all</em> of those estimators to get the two probability estimates, if you want! But more on that later.</p>
<p>The benefit of expanding your toolbox of potential estimators is that most estimators are built with prediction in mind, and thus yield very good probability estimates to initiate our TMLE algorithm. When our goal as statisticians is to calculate effects on an outcome attributable to a treatment, it’s easy to shy away from these prediction-focused types of estimators, because most of them do not have any statistical theory to allow us to calculate valid confidence intervals.</p>
<p><strong>A huge selling point of TMLE is that it allows you to utilize prediction-focused (often non-parametric) estimators, but still obtain valid confidence intervals on your final estimate of the treatment’s effect.</strong> TMLE utilizes concepts from semi-parametric influence function theory to determine valid standard errors, and therefore valid confidence intervals, on estimates of treatment effects. This is not important unless you plan to tackle the math of TMLE, but if you do decide to venture into technical explanations, know that you’ll see references to influence functions <em>a lot</em>!</p>
<p>In other propensity score methods, like IPTW, we can only obtain valid confidence intervals if we obtain our propensity score using pre-specified parametric models. For example, we fit a logistic regression for our treatment predicted by five pre-specified baseline covariates. Using a logistic model like this to calculate the propensity score is not only placing a strong distributional assumption on our data, but it is limited in its ability to take in high-, or even medium-dimensional data. When we use estimators that are well equipped for very “wide” data and perform variable selection, we obtain better overall estimates for our treatment effect of interest.</p>
<p>There are a few other major benefits to TMLE. For one, it has very good bias-variance properties, and those properties are “robust,” or “resistant to” model mispecification, i.e. having the wrong type of estimator or the wrong variables in your estimation of either the treatment or outcome. Another benefit is that if you are able to go through a causal identification process of the research question and available data (a concept I won’t discuss further, since it’s a separate realm of the problem), you’ll have a causal interpretation of your average treatment effect estimate.</p>
</div>
<div id="a-real-world-application-of-tmle" class="section level1">
<h1>A Real World Application of TMLE</h1>
<pre class="r"><code>library(dplyr, warn.conflicts=F)</code></pre>
<p>Here I’ll be using a data set from the ???. EXPLAIN DATA aND goal</p>
<p>I chose this data set because it is the same data used in a really good resource if you want to do a deeper dive in Targeted Learning:</p>
<pre class="r"><code>washb_data &lt;- data.table::fread(&quot;https://raw.githubusercontent.com/tlverse/tlverse-data/master/wash-benefits/washb_data.csv&quot;,
                    stringsAsFactors = TRUE)</code></pre>
<p>Before we can run a TMLE analysis, we need to clean the data a bit. The <code>tmle</code> function requires a binary treatment, so I’ll need to turn the treatment data from character strings to binary 0/1 variables. I’m only interested right now in women who recieved the treatment of Nutrition and Hand washing, and comparing that to the control women, so I’ll filter out the appropriate subjects and make my data binary.</p>
<p>To use <code>tmle</code>, your data structure should be:</p>
<ul>
<li><p>Wide (each row is one observation)</p>
<ul>
<li><p>No factors (all categorical variables should be transformed to dummy/indicator columns using a function like <code>model.matrix()</code></p></li>
<li><p>No missing data (I usually make a new column indicating whether the value was missing, and then impute at the mean or median for continuous variables)</p></li>
</ul></li>
</ul>
<pre class="r"><code>dat_clean &lt;- 
  washb_data %&gt;%
  filter(tr %in% c(&quot;Control&quot;, &quot;Nutrition + WSH&quot;)) %&gt;%
  mutate(tr = case_when(tr == &quot;Control&quot; ~ 0,
                        TRUE ~ 1)) %&gt;%
  mutate_at(vars(one_of(c(&quot;momage&quot;,&quot;momheight&quot;))), list(miss =~ ifelse(is.na(.), 1, 0))) %&gt;%
  mutate_at(vars(one_of(&quot;momage&quot;,&quot;momheight&quot;)), list( ~ ifelse(is.na(.), mean(., na.rm=T), .))) %&gt;%
  model.matrix(~ . + 0, data = .) %&gt;%
  as.data.frame()</code></pre>
<p>Once I’ve cleaned my data, I make vectors specifying my treatment, outcome, and baseline covariates. In the TMLE literature, and in this package, the notations are:</p>
<ul>
<li><p>Outcome: <code>Y</code></p>
<ul>
<li><p>Treatment: <code>A</code></p></li>
<li><p>Confounders: <code>W</code></p></li>
</ul></li>
</ul>
<p>In this data set, our outcome is the variable <code>whz</code>, our treatment is the variable <code>tr</code>, and our baseline confounders are all the other variables in our data set.</p>
<pre class="r"><code>Y &lt;- dat_clean$whz
A &lt;- dat_clean$tr
W &lt;- dat_clean %&gt;% dplyr::select(-whz, -tr)</code></pre>
<p>Once we’ve done that, we can get our TMLE estimate of the average treatment effect! Here, I’m only inputting the</p>
<pre class="r"><code>tmlefit_default &lt;- tmle::tmle(Y, A, W)
tmlefit_default</code></pre>
<p>Here, I’m going to specify the kinds of estimators I want to use to get my two important estimates: the expected outcome and the probability of the exposure.</p>
<p>I’ve chosen to call the functions <code>glm</code> for a generalized linear model, <code>glmnet</code> for penalized regression, <code>ranger</code> for random forests, and <code>xgboost</code> for extreme gradient boosting.</p>
<p>I’m going to use <em>all</em> of these estimators to estimate the</p>
<pre class="r"><code>SL_library &lt;- c(&quot;SL.glm&quot;,
                &quot;SL.glmnet&quot;,
                &quot;SL.ranger&quot;,
                &quot;SL.xgboost&quot;)</code></pre>
<p>We’re going to specify those libraries in the arguments <code>Q.SL.library</code> and <code>g.SL.library</code>. These arguments sound a bit scary, but they are just what the notation in TMLE literature is – Q refers to the estimation for the outcome given treatment and covariates, and g refers to the estimation of the probability of the treatment.</p>
<pre class="r"><code>tmlefit &lt;- tmle::tmle(Y, A, W,
                Q.SL.library = SL_library, g.SL.library = SL_library)
tmlefit</code></pre>
<p>To understand how the various machine learning models are combining, you should look into a type of ensemble learning called stacking, or “superlearning.” I have a slideshow that you could look at <a href="https://github.com/hoffmakl/sl3-demo/blob/master/superlearning_slides_no_animation.pdf">here</a>, but there are plenty of other resources online.</p>
<p>This is obviously not a super technical post, and it was not intended to be, but I hope that it may catch your interest to learn more about the complexities of TMLE and try it out in your next analysis. I plan to write a few similar posts on what to do if your outcomes are survival or longitudinal data. In the meantime, you may find the more technical tutorial on TMLE helpful:</p>
<p>or, “The Hitchiker’s Guide to Targeted Learning” is an excellent, still-in-progress, resource for learning TMLE and many other targeted learning.</p>
<p>Learn about causal inference,</p>
<p>we should be estimating answers for questions of actual interest, rather than debiasing our results.</p>
<p><strong>Bias</strong>: The difference between the true value of a parameter and the estimated value.</p>
<p><strong>Consistency</strong>: The bias of an estimator decreases to 0 as sample size approaches infinity.</p>
<p><strong>Efficiency</strong>: The variance of an estimator is as small as possible as sample size approaches infinity.</p>
<p><strong>Double robust</strong>: If either of</p>
<p>Causal inference, at a bird’s eye view, involves a process of:</p>
<ol style="list-style-type: decimal">
<li><p>Defining a question and the causal parameter, or causal estimand, of interest (for example, we might want to know the difference in COVID-19 infection rates if everyone did wear a mask compared to if everyone did not wear a mask).</p></li>
<li><p>Using causality tools (for example, Directed Acyclic Graphs or Non Parametric Structrual Equations) and assumptions (exchangeability, consistency, and positivity) to determine whether we can write our causal estimand of interest in terms of the data (using expectations and random variables). If we can do this, we say our causal estimand is <strong>identifiable</strong>, and we can make the leap that a <em>statistical estimand</em> (i.e. expectations and random variables) is a true representation of what we would see in a world that allows us to actually observe all the parallel, or counterfactual, outcomes.</p></li>
<li><p>Once we have a statistical estimand, we can consider the statistical estimation algorithms available to estimate it (typically we weigh them in terms of bias and variance properties, and perhaps computational requirements), and then go on to estimate it.</p></li>
</ol>
<p>There’s thousands of books and papers that elaborate on those three points above, but the main takeaway is this:</p>
<blockquote>
<p><strong>TMLE focuses on Step 3 only.</strong> It is a <strong>statistical estimation algorithm</strong> that <em>allows</em>, but <em>does not require</em> statistical estimands to have a causal interpretation.</p>
</blockquote>
</div>
<div id="a-comparison-with-g-computation-and-iptw" class="section level1">
<h1>A comparison with G-Computation and IPTW</h1>
</div>
<div id="references" class="section level1">
<h1>References:</h1>
</div>
